### ISSUE TITLE
[ Bug ] Pretendard 폰트 미적용 버그

### ISSUE THREAD

**Issue by whitedev7773** [LikeLion-FireFox/asparagus-frontend#5]
## 🛠️ 발견된 버그 기능
`@import`로 불러오는 Pretendard 웹폰트 적용이 안되는 현상

## 🌎 발견된 환경
Pretendard 폰트가 otf,ttf로 설치되어있지 않는 컴퓨터

**Comment by whitedev7773** [comment]
1. global.js
- 기존 @import를 비활성화함
- *로 전체 element에 폰트 적용
```css
// @import url('https://cdn.jsdelivr.net/gh/orioncactus/pretendard/dist/web/static/pretendard.css');
  
  * {
    font-family: 'Pretendard', sans-serif;
  }
```

2. index.html
- 폰트를 불러오는 새로운 link 태그 주가
```html
<link rel="stylesheet" as="style" crossorigin href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/static/pretendard.min.css" />
```
